import { useEffect, useMemo, useState } from "react";
import { JsonViewer } from "../../components/viewers/JsonViewer";
import { CodingPhasePanel } from "../../components/workflow/CodingPhasePanel";
import { StepPage, type StepTabDef } from "../../components/workflow/StepPage";
import type { ArtifactKey } from "../../services/artifactApi";
import { fetchStep7Deviations, type Step7DeviationRow } from "../../services/stepApi";
import { navigateToStep } from "../../utils/hashRoute";

interface CodingStepPageProps {
  studyId: string;
  codingPhaseAccepted: boolean;
  goPrev?: () => void;
  prevLabel?: string;
  tabParam?: string;
}

/** #/coding — gated coding workspace with per-deviation context artifacts. */
export function CodingStepPage({
  studyId,
  codingPhaseAccepted,
  goPrev,
  prevLabel,
  tabParam
}: CodingStepPageProps): JSX.Element {
  const trimmed = studyId.trim();
  const [rows, setRows] = useState<Step7DeviationRow[]>([]);
  const [selectedDeviationId, setSelectedDeviationId] = useState("");

  useEffect(() => {
    let cancelled = false;
    setRows([]);
    setSelectedDeviationId("");
    if (!trimmed) {
      return;
    }
    fetchStep7Deviations(trimmed)
      .then((response) => {
        if (cancelled) {
          return;
        }
        setRows(response.rows);
        const firstAccepted = response.rows.find((row) => row.status === "accepted");
        setSelectedDeviationId(firstAccepted?.deviation_id ?? "");
      })
      .catch(() => {
        // review data unavailable; gate text covers it
      });
    return () => {
      cancelled = true;
    };
  }, [trimmed]);

  const resolved = rows.filter((row) => row.status === "accepted" || row.status === "rejected").length;
  const acceptedRows = useMemo(() => rows.filter((row) => row.status === "accepted"), [rows]);
  const resolvedPct = rows.length > 0 ? Math.round((resolved / rows.length) * 100) : 0;

  const gateBanner = !codingPhaseAccepted ? (
    <div className="step-banner-warn">
      <p>
        Coding unlocks after the Review phase is accepted ({rows.length > 0 ? `${resolvedPct}% resolved` : "no review data yet"}).
      </p>
      <button type="button" className="button button-secondary" onClick={() => navigateToStep("review-and-finalize")}>
        Go to Review
      </button>
    </div>
  ) : undefined;

  const tabs = useMemo<StepTabDef[]>(() => {
    if (!trimmed || !codingPhaseAccepted) {
      return [];
    }
    return [
      {
        id: "context",
        label: "Deviation context",
        isArtifact: true,
        render: () => (
          <div className="master-detail">
            <nav className="master-detail-list" aria-label="Accepted deviations">
              {acceptedRows.length === 0 ? <p className="step7-muted">No accepted deviations.</p> : null}
              {acceptedRows.map((row) => (
                <button
                  key={row.deviation_id}
                  type="button"
                  className={`master-detail-item ${row.deviation_id === selectedDeviationId ? "master-detail-item-active" : ""}`}
                  onClick={() => setSelectedDeviationId(row.deviation_id)}
                >
                  <span className="master-detail-item-title">{row.deviation_id}</span>
                  <span className="step7-muted">{row.rule_id}</span>
                </button>
              ))}
            </nav>
            <div className="master-detail-content">
              {selectedDeviationId ? (
                <JsonViewer
                  key={`context-${selectedDeviationId}`}
                  studyId={trimmed}
                  artifact={`coding-context:${selectedDeviationId}` as ArtifactKey}
                  emptyMessage="No grounding context artifact for this deviation (generated by PD-spec import grounding)."
                />
              ) : (
                <p className="step7-muted">Select a deviation.</p>
              )}
            </div>
          </div>
        )
      },
      {
        id: "enrichment",
        label: "Protocol enrichment",
        isArtifact: true,
        render: () =>
          selectedDeviationId ? (
            <JsonViewer
              key={`enrichment-${selectedDeviationId}`}
              studyId={trimmed}
              artifact={`coding-enrichment:${selectedDeviationId}` as ArtifactKey}
              emptyMessage="No enrichment artifact for this deviation (generated by PD-spec enrich)."
            />
          ) : (
            <p className="step7-muted">Select a deviation in the Deviation context tab.</p>
          )
      }
    ];
  }, [trimmed, codingPhaseAccepted, acceptedRows, selectedDeviationId]);

  return (
    <StepPage
      title="Coding"
      description="Implement programmable checks from the accepted deviations."
      status={codingPhaseAccepted ? "done" : "pending"}
      statusDetail={rows.length > 0 ? `${acceptedRows.length} accepted` : undefined}
      hasOutput={codingPhaseAccepted}
      banner={gateBanner}
      controls={codingPhaseAccepted ? <CodingPhasePanel studyId={studyId} /> : undefined}
      tabs={tabs}
      initialTabId={tabParam}
      onPrev={goPrev}
      prevLabel={prevLabel}
    />
  );
}
